baseURL = 'https://fmaf-cms.netlify.app/'
languageCode = 'en-us'
title = 'Free Meals Appalachia'
theme = 'hugo-flex'

[params]
color = "green"
width = "42rem"
divider = "\\2500\\2500"
footer = '<a href="https://github.com/freemealsaf/fmaf-cms" target="_blank">Source Code</a>'
rss = "To subscribe to this RSS feed, copy its address and paste it into your favorite feed reader."
favicon = false
noClasses = false
katex = "0.16.10"
headingoffset = 0
linkicons = false
summaries = true
schema = false
opengraph = false
twittercards = false
math = false

[params.utterances]

[params.netlify]
honeypot = true
recaptcha = false

[params.mathdelim]
block = [["\\[", "\\]"], ["$$", "$$"]]
inline = [["\\(", "\\)"]]

[markup.highlight]
noClasses = false

[markup.goldmark.extensions.passthrough]
enable = false

[markup.goldmark.extensions.passthrough.delimiters]
block = [["\\[", "\\]"], ["$$", "$$"]]
inline = [["\\(", "\\)"]]

[[menu.main]]
name = "About"
pageRef = "/about"
weight = 1

[[menu.main]]
name = "News"
pageRef = "/news"
weight = 2

[[menu.main]]
name = "Contact"
pageRef = "/contact"
weight = 3

[[menu.main]]
name = "Donate"
pageRef = "/donate"
weight = 4

[[menu.main]]
name = "Volunteer"
pageRef = "/Volunteer"
weight = 5

#
#[[menu.main]]
#name = "Tags"
#pageRef = "/tags"
#weight = 3

#[[menu.main]]
#name = "Categories"
#pageRef = "/categories"
#weight = 4

#[[menu.main]]
#name = "RSS"
#pageRef = "/"
#weight = 5

#[[menu.main.params]]
#format = "rss"

[outputFormats.rss]
mediatype = "application/rss+xml"
baseName = "feed"
